ctest:
  stage: test
  image: rikorose/gcc-cmake:latest
  script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest -V

valgrind:
  stage: test
  image: obraun/algdati-valgrind-ci:latest
  script:
    - mkdir build && cd build
    - cmake ..
    - make
    - valgrind --leak-check=full --error-exitcode=1 ./test/testList
